# Generated by Django 5.1.4 on 2024-12-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_userprofile_password_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reg_number',
            field=models.CharField(default='error', max_length=100),
            preserve_default=False,
        ),
    ]
